### ISSUE TITLE
  File "/home/anthony/work/third/stable-diffusion-good/Face2Diffusion/src/modules.py", line 51, in forward     x = torch.cat([x,exp],-1)        

### ISSUE THREAD

**Issue by anthonyyuan** [mapooon/Face2Diffusion#3]
File "/home/anthony/work/third/stable-diffusion-good/Face2Diffusion/src/modules.py", line 51, in forward
    x = torch.cat([x,exp],-1)
        ^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Tensors must have same number of dimensions: got 4 and 2

**Comment by mapooon** [comment]
Thank you for reporting your issue.
In what case did this error occur?
Also, please check the shapes of x and exp.
The shape of x should be (batch size, 1536) and that of exp should be (batch size, 64).
